services:
  - type: web
    name: freqtrade-bot
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      freqtrade install-ui --userdir user_data
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0